# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Seda' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Seda
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Functions'
  pod 'IQKeyboardManagerSwift'
  pod 'CardScan'
  pod 'CardScan/Stripe'

end
